export const INITIAL_FOODLIST = 'INITIAL_FOODLIST';
export const UPDATE_FOODLIST = 'UPDATE_FOODLIST';
export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
export const CLEAR_FOODARRAY = 'CLEAR_FOODARRAY';

export const FOODITEM = 'FOODITEM';